export const ON_INITIAL_LOAD = "ON_INITIAL_LOAD";

export const ON_SUCCESS_ADD_NEW = "ON_SUCCESS_ADD_NEW";
export const ON_INIT_ADD_NEW = "ON_INIT_ADD_NEW";
export const ON_FAIL_ADD_NEW = "ON_FAIL_ADD_NEW";
export const ON_FINISH_ADD_NEW = "ON_FINISH_ADD_NEW";

export const ON_CHECKBOX_CHANGE = "ON_CHECKBOX_CHANGE";

export const ON_COURSE_DELETE = "ON_COURSE_DELETE";
